version: "3.8"

services:
  rahoot:
    #image: ralex91/rahoot:latest
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./config:/app/config # Path to your game config
    environment:
      - WEB_ORIGIN=*
      - SOCKET_URL=http://192.168.1.2:3001
